jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  nodes:
  - permanent:
      labelString: "ec2-worker ec2"
      launcher:
        ssh:
          credentialsId: "jenkins-worker-pk"
          host: "jenkins-worker"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "ec2-worker"
      remoteFS: "/home/ubuntu/jenkins"
      retentionStrategy: "always"
  numExecutors: 0
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "jenkins-petclinic-token"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "maven-3.9.2"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.2"
jobs:
  - script: >
      pipelineJob('Petclinic-Provision-Up') {
        description('Configured in JCasC with JobDSL')
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Up")
          }
        }
      }
  - script: >
      pipelineJob('Petclinic-Provision-Down') {
        description('Configured in JCasC with JobDSL')
        parameters {
          booleanParam('DESTROY_DB', false, 'Check out to permanently delete database resource')
        }
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Down")
          }
        }
      }
  - script: >
      pipelineJob('Petclinic-Provision-Plan') {
        description('Configured in JCasC with JobDSL')
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Plan")
          }
        }
      }
  - script: >
      multibranchPipelineJob('Petclinic-PR') {
        // dissable pipeline by defalut
        configure {
          it / disabled << 'true' // dissable pipeline by defalut
        }
        description('Job dissabled by default.\nEnable this job when configuration is finished. \n\n Configured in JCasC with JobDSL')
        branchSources {
          branchSource{
            source{
              github {
                repoOwner('lipalipinski')
                repository('spring-petclinic.git')
                configuredByUrl(true)
                credentialsId('jenkins-petclinic-token-user')
                repositoryUrl('https://github.com/lipalipinski/spring-petclinic.git')
                traits {

                  // Discovers branches on the repository.
                  gitHubBranchDiscovery {
                  // Determines which branches are discovered.
                  strategyId(1)
                  }
                }
              }
            }
          }
        }
        factory{
          remoteJenkinsFileWorkflowBranchProjectFactory{
            fallbackBranch("main")
            localMarker("")
            matchBranches(false)
            remoteJenkinsFile("Jenkinsfile-PR")
            remoteJenkinsFileSCM{
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
          }
        }
        triggers {
          periodicFolderTrigger{
            interval('5m')
          }
        }
      }
  - script: >
      pipelineJob('Petclinic-Deploy') {
        description('Configured in JCasC with JobDSL')
        parameters {
          string {
            name("APP_TAG")
            description("Provide a tag of an app image to be deployed")
            trim(true)
          }
        }
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Deploy")
          }
        }
      }