jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  nodes:
  - permanent:
      labelString: "ec2-worker ec2"
      launcher:
        ssh:
          credentialsId: "jenkins-worker-pk"
          host: "jenkins-worker"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "ec2-worker"
      numExecutors: 2
      remoteFS: "/home/ubuntu/jenkins"
      retentionStrategy: "always"
  numExecutors: 0
jobs:
  - script: >
      pipelineJob('Petclinic-Provision-Up') {
        description('Configured in JCasC with JobDSL')
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Up")
          }
        }
      }
  - script: >
      pipelineJob('Petclinic-Provision-Down') {
        description('Configured in JCasC with JobDSL')
        definition {
          cpsScm {
            lightweight(false)
            scm {
              gitSCM{
                userRemoteConfigs{
                  userRemoteConfig{
                    name("") //Custom Repository Name or ID
                    url("https://github.com/lipalipinski/capstone-project-2-ci-cd.git") //URL for the repository
                    refspec("") // Branch spec
                    credentialsId("") // Credential ID. Leave blank if not required
                  }
                }
                branches{
                  branchSpec{
                    name("refs/heads/main")
                  }
                }
                browser{} // Leave blank for default Git Browser
                gitTool("") //Leave blank for default git executable
              }
            }
            scriptPath("Jenkinsfile-Down")
          }
        }
      }